name: text_to_picture_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  image_picker: ^1.1.0
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.3
  image_gallery_saver: ^2.0.3
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
  fonts:
    - family: maruburi
      fonts:
        - asset: assets/font/maru_buri/MaruBuri-ExtraLight.ttf
          weight: 200
        - asset: assets/font/maru_buri/MaruBuri-Light.ttf
          weight: 300
        - asset: assets/font/maru_buri/MaruBuri-Regular.ttf
          weight: 400
        - asset: assets/font/maru_buri/MaruBuri-Bold.ttf
          weight: 500
        - asset: assets/font/maru_buri/MaruBuri-SemiBold.ttf
          weight: 600
    - family: chosunGu
      fonts: 
        - asset: assets/font/chosun_gu/ChosunGu.TTF
          weight: 300
    - family: kopubBatang
      fonts: 
        - asset: assets/font/kopub/batang/KoPub-Batang-Medium.ttf
          weight: 300
    - family: kopubDotum
      fonts: 
        - asset: assets/font/kopub/dotum/KoPub-Dotum-Medium.ttf
          weight: 300
    - family: okja
      fonts: 
        - asset: assets/font/okja/Mail-Okja-Regular.ttf
          weight: 300
    - family: pretendard
      fonts: 
        - asset: assets/font/pretendard/Pretendard-Regular.otf
          weight: 300
    - family: ridiBatang
      fonts: 
        - asset: assets/font/ridi_batang/RIDIBatang-Regular.otf
          weight: 300
